# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-20.10"
  
  # Provision
  config.vm.provision :shell, :path => "install.sh"

  # Pour accéder à la VM depuis l'hote
  config.vm.network :forwarded_port, guest: 8081, host: 8081

  config.vm.network "public_network", ip: "192.168.1.12"

  # Shared folder
  config.vm.synced_folder "project/", "/home/project", create: true

end

