# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-20.10"
  
  # Provision
  config.vm.provision :shell, :path => "install.sh"

  # Pour accéder à la VM depuis l'hote
  config.vm.network :forwarded_port, guest: 8080, host: 8014

  #config.vm.network "public_network", ip: "192.168.1.14"
  config.vm.network "private_network", :type => 'dhcp'

  config.vm.network "private_network", :type => 'dhcp'

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
    vb.customize ["modifyvm", :id, "--nic3", "natnetwork"]
    vb.customize ["modifyvm", :id, "--nat-network3", "NatNetwork"]
  end

  # Shared folder
  config.vm.synced_folder "project/", "/home/project", create: true

end

# Donner accès à internet pour installer les paquets python


